// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIj5D-mKN79EM4_y4rBrbPzDlDxruru8g',
    appId: '1:975796688747:web:777d4129174de58d05de2e',
    messagingSenderId: '975796688747',
    projectId: 'chatapp-38008',
    authDomain: 'chatapp-38008.firebaseapp.com',
    storageBucket: 'chatapp-38008.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVmQSYVawgVff4Gc25wF8Fb3BnEU8arag',
    appId: '1:975796688747:android:a7066f97e700d6e905de2e',
    messagingSenderId: '975796688747',
    projectId: 'chatapp-38008',
    storageBucket: 'chatapp-38008.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4bqVhxJUwg5X4OCNY5D1SCXALk2pMVs',
    appId: '1:975796688747:ios:48d61284e179813805de2e',
    messagingSenderId: '975796688747',
    projectId: 'chatapp-38008',
    storageBucket: 'chatapp-38008.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4bqVhxJUwg5X4OCNY5D1SCXALk2pMVs',
    appId: '1:975796688747:ios:48d61284e179813805de2e',
    messagingSenderId: '975796688747',
    projectId: 'chatapp-38008',
    storageBucket: 'chatapp-38008.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIj5D-mKN79EM4_y4rBrbPzDlDxruru8g',
    appId: '1:975796688747:web:1e01d790f8f73dfd05de2e',
    messagingSenderId: '975796688747',
    projectId: 'chatapp-38008',
    authDomain: 'chatapp-38008.firebaseapp.com',
    storageBucket: 'chatapp-38008.appspot.com',
  );
}
